# Generated by Django 5.2.4 on 2025-07-30 09:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tool_type', models.CharField(choices=[('ERP', 'Enterprise Resource Planning'), ('CRM', 'Customer Relationship Management'), ('INV', 'Inventory Management'), ('ACC', 'Accounting')], max_length=3)),
                ('description', models.TextField()),
                ('access_url', models.URLField()),
                ('tutorial_url', models.URLField()),
                ('is_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('MSME', 'MSME Owner'), ('BUYER', 'Large Buyer'), ('LENDER', 'Financial Institution'), ('ADVISOR', 'Business Advisor')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Delhi', max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(max_length=100)),
                ('industry_sector', models.CharField(max_length=100)),
                ('annual_procurement_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preferred_supplier_criteria', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('items', models.JSONField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buyerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningcourse')),
            ],
        ),
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(max_length=100)),
                ('financial_products_offered', models.TextField()),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSMEProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('business_type', models.CharField(max_length=100)),
                ('industry_sector', models.CharField(max_length=100)),
                ('years_in_operation', models.IntegerField()),
                ('annual_turnover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_count', models.IntegerField()),
                ('products_services', models.TextField()),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('udhyam_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('tenure_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('documents', models.JSONField()),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lenderprofile')),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.msmeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDiscountingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.msmeprofile')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='msme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.msmeprofile'),
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('factors', models.JSONField()),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.msmeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MSMEToolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.msmeprofile')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businesstool')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('expected_price_range', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buyerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_time', models.CharField(max_length=100)),
                ('terms', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('AWARDED', 'Awarded')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.msmeprofile')),
                ('procurement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.procurementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moq', models.IntegerField(default=1)),
                ('specifications', models.JSONField()),
                ('images', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.msmeprofile')),
            ],
        ),
    ]
