# Generated by Django 5.2.4 on 2025-07-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='annual_procurement_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='msmeprofile',
            name='annual_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='msmeprofile',
            name='business_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='msmeprofile',
            name='business_type',
            field=models.CharField(default='Manufacturing', max_length=100),
        ),
        migrations.AlterField(
            model_name='msmeprofile',
            name='employee_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='msmeprofile',
            name='industry_sector',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='msmeprofile',
            name='products_services',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='msmeprofile',
            name='years_in_operation',
            field=models.IntegerField(default=1),
        ),
    ]
